export * from '@/views/CreditsView';
export * from '@/views/ErrorView';
export * from '@/views/HomeView';
export * from '@/views/MoviesView';
export * from '@/views/MovieView';
export * from '@/views/ReviewsView';
export * from '@/views/SearchView';
export * from '@/views/TrendingView';
export * from './Genre/GenreView';
